### ISSUE TITLE
CopyFeature.IGNORE_PRIMITIVE_NULL_SOURCE_VALUE失效

### ISSUE THREAD

**Issue by sj853** [yangtu222/BeanUtils#10]
CopyFeature.IGNORE_PRIMITIVE_NULL_SOURCE_VALUE 没有起到作用
我在 target的class中 设置 @BeanCopySource(source = Target.class, features = CopyFeature.IGNORE_PRIMITIVE_NULL_SOURCE_VALUE)

在进行copy的时候  null还是覆盖了

**Comment by yangtu222** [comment]
Hi, 您好。
IGNORE_PRIMITIVE_NULL_SOURCE_VALUE Ignore copy object type null to primitive type. e.g. Copy null (Integer type) to int. By default this feature is disabled, so we can debug where the pointer is null by thrown exception.
意思是说，从null到primitive type类型时忽略，避免抛出异常。
例如source是Integer，但是是null，target是int。
不知道是不是你想要的用法，还是有其他的错误。望回复。

**Comment by sj853** [comment]
你好 感谢你有focus 到    我试着从 A copy 到 B    A 里面有一些null 不想复制过去  比如 我要做一个更新操作

发送自 Windows 10 版邮件应用

发件人: Tu Yang
发送时间: 2018年7月19日 19:48
收件人: yangtu222/BeanUtils
抄送: elemeNT; Author
主题: Re: [yangtu222/BeanUtils] CopyFeature.IGNORE_PRIMITIVE_NULL_SOURCE_VALUE失效 (#10)

Hi, 您好。

**Comment by sj853** [comment]
明白了 只是primitive type 哦   我以为可以是任意类型
我还是举个例子哈
比如 我想从对象A 复制到 对象B   (具体场景是  我做更新操作  但只传我想更新的属性)
这个时候 A里面所有为null的属性(任何类型) 不想复制到B 去

**Comment by yangtu222** [comment]
hi，您好。想探讨下需求。
对于更新的属性，如果是null，也可以理解成更新成空啊。如果从这个角度来看，我们无法分辨源数据为空，是更新为空，还是无数据。
另外，对于primitive type来说，由于它无法为空，它的值，就更无法知晓它是更新过的数据，还是无需变动的数据。
因此，要想只传更新的属性，从逻辑判断的角度来看还无法进行。当然，如果说是null值不做传递的话，倒是可行的，但只是局限于Object对象，对primitive type类型来说无效。

**Comment by yangtu222** [comment]
Hi, 您好。v1.0.7加入了IGNORE_ALL_NULL_SOURCE_VALUE属性支持。您可以尝试下。

**Comment by sj853** [comment]
好的 感谢 我试试

**Comment by sj853** [comment]
IGNORE_ALL_NULL_SOURCE_VALUE 貌似没有起作用   
首先感谢你的回馈   如果加了 IGNORE_ALL_NULL_SOURCE_VALUE 是否跟IGNORE_PRIMITIVE_NULL_SOURCE_VALUE  又存在一些冲突呢
比如 我希望除了 PRIMITIVE 的 其他为NULL 才不复制

**Comment by yangtu222** [comment]
Hi, IGNORE_ALL_NULL_SOURCE_VALUE 包含了IGNORE_PRIMITIVE_NULL_SOURCE_VALUE。
