### ISSUE TITLE
整体功能不错，提个建议，里面的log级别修改为debug是不是更适合一些呢

### ISSUE THREAD

**Issue by waterlang** [yangtu222/BeanUtils#11]
如果每次操作对象的一次copy都会打印info级别的log有点伤io性能，这些对于开发者来讲大多时候不是必须的

**Comment by yangtu222** [comment]
@waterlang 你好！
在BeanCopyConfig中，可以设置输出log的级别，以及dump信息的级别。在开发时可以打开这些，用于跟踪调试；在产品时可以设置为关闭，log就不会输出。

**Comment by waterlang** [comment]
@yangtu222  恩好的，谢谢你了

**Comment by handy-git** [comment]
你好,请问这个BeanCopyConfig怎么配置,是去源码里修改吗
