### ISSUE TITLE
关于@CopyProperty中optionClass循环使用的问题

### ISSUE THREAD

**Issue by sj853** [yangtu222/BeanUtils#12]
我有个一个类(比如region表达省市区县村等等)
里面相应的有 parent 和children
![image](https://user-images.githubusercontent.com/3139596/43671289-a81b82f0-97c9-11e8-9b3b-2e43ffe433a0.png)
在做copy的时候 我希望 copy  父的父(排除父的子)  以及 子的子(排除子的父)  如下图
父中不要子 的option
![image](https://user-images.githubusercontent.com/3139596/43671297-d66dcc26-97c9-11e8-913e-1b0a54f805a2.png)
子中不要父的option
![image](https://user-images.githubusercontent.com/3139596/43671300-df7b2e4e-97c9-11e8-9c35-4dadcfd74352.png)

目前子的子 循环都OK 的 
但是父的父  copy死循环了   大概是 option中的  @CopyProperty 中的optionclass没起作用
![image](https://user-images.githubusercontent.com/3139596/43671316-19b6f886-97ca-11e8-9ec6-2034c4aff626.png)

现在我想了一个办法 我复制了一个 PlacePO2DTOWithoutChildren 命名为 PlacePO2DTOWithoutChildren2
![image](https://user-images.githubusercontent.com/3139596/43671322-35e39ee2-97ca-11e8-8800-3dfc36740dfe.png)

虽然没有死循环了 但是 我有 至少 5个层级  现在只能拿到3个层级 再上级就不copy了 很奇怪
所以 我有尝试  PlacePO2DTOWithoutChildren 用PlacePO2DTOWithoutChildren 2
PlacePO2DTOWithoutChildren 2 用 PlacePO2DTOWithoutChildren 3 一直用到5
得到的结果还是 只有3个层级    copy源数据都是OK的

**Comment by yangtu222** [comment]
Hi, 问题似乎出在log dump的地方。可以尝试下BeanCopyConfig的dumpOption，修改为AutoDumpNone试试看。
另外，只copy 3各层次的问题，似乎不是BeanCopy的问题，还需要你查下代码，看是不是有null，导致层次断裂。
log dump导致死循环的问题，我将发布一个新的release，当做bug来fix。

**Comment by sj853** [comment]
嗯 试了试  关闭了 log 确实OK了
