### ISSUE TITLE
开发模式下提供关闭缓存的选项

### ISSUE THREAD

**Issue by chenchi2038** [yangtu222/BeanUtils#13]
开发时修改了代码之后，有各种技术来重新加载变更后的代码而无需重启程序，能够大大的提升开发效率，但是BeanUtils会缓存映射关系，导致修改之后的代码无法生效，是否能够提供一个配置，在开发阶段关闭缓存？

**Comment by yangtu222** [comment]
reset缓存的功能会随着其他的功能提供。请参考v1.0.9的BeanCopyConfig.setBeanCopyConfig(null);使用。
目前v1.0.8的此函数有bug，达不到reset的效果。

**Comment by yangtu222** [comment]
v1.0.9发布了，你可以试下。
