### ISSUE TITLE
多个对象转同一个对象

### ISSUE THREAD

**Issue by enjoymore** [yangtu222/BeanUtils#15]
假设 有AVO,BVO 都可能转CInfo,Cinfo内部有个字段D是枚举需要打CopyProperty注解，但是AVO有这个字段，BVO没有这个字段，能不能 转换的时候没有对应的属性，就直接转换结果为Null不要直接抛异常

**Comment by yangtu222** [comment]
Hi, 建议使用Option Class方式来用。
ToBean toBean = BeanCopyUtils.copyBean(fromBean, ToBean.class, ToBeanOption.class);
在ToBeanOption中将不需要转换的属性使用CopyProperty标记成ignore即可。
