### ISSUE TITLE
Option Class的方式使用BeanCopySource,如果target Object类中存在CopyCollection可能会报错 #7

### ISSUE THREAD

**Issue by a-nuo** [yangtu222/BeanUtils#17]
场景是，从多个source 对象拷贝不同的属性到target Object
如果target Object中存在CopyColletion配置，而OptionClass中不存在这个字段，则会报错，提示缺少对应的字段异常

**Comment by a-nuo** [comment]
按#6 #7 中的建议的方式去做的

**Comment by yangtu222** [comment]
如果target Object中存在CopyColletion配置，那么就是说必须要从source中获取到。如果source中没有，或者不做拷贝，可以在OptionClass加入这个字段，然后标记ignore。

**Comment by a-nuo** [comment]
这样确实可以。
如果target Object 中CopyColletion字段比较多，而且source对象也比较多的话，如果直接根据OptionClass中的字段做拷贝，这样可以省略许多的手动配置。
我理解OptionClass的配置相当于覆盖target Object中的映射配置，不知道这样理解是否合适

**Comment by a-nuo** [comment]
如果可以理解为OptionClass覆盖target Object 中的映射配置，是否一个默认以OptionClass中的配置为准，OptionClass不存在的配置和字段，就不再继续拷贝，这样也比较符合多个Source 拷贝到 target 的实际场景，毕竟多个Source 字段重合的可能性不太大

**Comment by yangtu222** [comment]
OptionClass不存在的配置和字段，采取的是默认拷贝方式。否则每个OptionClass都要把所有的字段都填入才能保证拷贝完整。为了方便配置，OptionClass中定义的都是需要做特殊处理的字段即可，默认支持的拷贝方式可以不用写入。对于不想继续拷贝的，属于特殊处理的范围，需要加入ignore标记。
