### ISSUE TITLE
可以提供一个忽略属性大小写的copy入口吗

### ISSUE THREAD

**Issue by zhangdongkun** [yangtu222/BeanUtils#21]
您好，可以提供一个全局忽略大小写的copy 方法吗
比如
public class ClassA {
    private String aa;
}
public class ClassA {
    private String aA;
}
aa 和 AA ,Aa，aA可以互相赋值

**Comment by yangtu222** [comment]
hi，可以通“过”改名”的方法支持：
设置@CopyProperty(property="aA")的方式支持。
由于这个是基于标准JavaBean的规则，不建议做成通用的忽略大消息的支持。
