### ISSUE TITLE
并发情况下出现异常。

### ISSUE THREAD

**Issue by liangliang4ward** [yangtu222/BeanUtils#23]
使用option进行copy
` BeanCopyUtils.copyBean(fromBean,ToBean.class,BeanOption.class);`

异常信息：
```
Exception in thread "Thread-4" java.lang.NullPointerException
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:238)
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:199)
	at com.example.demo.beancopy.TestService.test(TestService.java:16)
	at com.example.demo.beancopy.TestYangtuBeanCopy.lambda$test2$0(TestYangtuBeanCopy.java:32)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yangtu222** [comment]
多谢报告，能否将大致的测试方式提供下？

**Comment by liangliang4ward** [comment]
`package com.example.demo.beancopy;

import com.tuyang.beanutils.annotation.BeanCopySource;
import com.tuyang.beanutils.annotation.CopyProperty;
import lombok.Data;

@BeanCopySource(source = FromBean.class)
@Data
public class BeanOption {
    @CopyProperty(property = "id", convertor = StringToIntegerConverter.class)
    private String id;
}`


`package com.example.demo.beancopy;

import lombok.Data;

/**
 * @author gll
 * 2019/5/28 16:05
 */
@Data
public class FromBean {

    private String id;
}
`


`package com.example.demo.beancopy;

import com.tuyang.beanutils.BeanCopyConvertor;

public  class StringToIntegerConverter implements BeanCopyConvertor<String,Integer> {

        @Override
        public Integer convertTo(String object) {
            return Integer.parseInt(object);
        }
    }`


`package com.example.demo.beancopy;

import lombok.Data;

/**
 * @author gll
 * 2019/5/28 16:05
 */
@Data
public class ToBean {

    String id;
}
`


`package com.example.demo.beancopy;

import com.example.demo.beanutils.Bean1;
import com.example.demo.beanutils.Bean2;
import com.example.demo.beanutils.InnerBean1;
import com.example.demo.beanutils.InnerBean2;
import com.tuyang.beanutils.BeanCopyUtils;
import lombok.SneakyThrows;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

/**
 * @author gll
 * 2019/4/22 19:26
 */
public class TestYangtuBeanCopy {


    @Test
    @SneakyThrows
    public void test2(){
        TestService testService = new TestService();


        List<Thread> threads = new ArrayList<>();
        for (int i=0;i<10;i++){
            threads.add(new Thread(()->{
                FromBean fromBean = new FromBean();
                fromBean.setId("1");
                System.out.println(testService.test(fromBean).getId());
            } ));
        }
        threads.forEach(e->e.start());
        threads.forEach(e-> {
            try {
                e.join();
            } catch (InterruptedException e1) {
                e1.printStackTrace();
            }
        });
    }


}
`

**Comment by yangtu222** [comment]
原因已找到，是在初始化拷贝器时，没有互斥处理。
临时避免方法为：避免在多线程中第一次使用，可在主线程调用一次拷贝后，再在多线程中使用。代码随后在更新。
多谢 @qq54903099
