### ISSUE TITLE
使用option 类 并且没有忽略空的情况下会报错，异常如下

### ISSUE THREAD

**Issue by zhangdongkun** [yangtu222/BeanUtils#24]
----测试代码如下

public static void main(String[] args) {
AdjustDto adjustDto = new AdjustDto();
adjustDto.setFlag(null);
adjustDto.setSerialNo(null);
PrpCadjustEntity prpCadjustEntity = new PrpCadjustEntity();
System.out.println(BeanUtilExt.copyBean(adjustDto, prpCadjustEntity,AdjustEntityOpt.class));
}
-----log below

Dump Bean Copy Property Mapping:
---------------------------------------------------------------------------------------------
From: [AdjustDto] To: [PrpCadjustEntity] Option: [AdjustEntityOpt]
---------------------------------------------------------------------------------------------
CopyFeature: (NONE)
---------------------------------------------------------------------------------------------
                        String getAdjustCode()|String setAdjustCode()
                              String getFlag()|String setFlag()
                    String getRiskAdjustCode()|String setRiskAdjustCode()
               BigDecimal getRiskAdjustValue()|BigDecimal setRiskAdjustValue()
                            Long getSerialNo()|long setSerialNo()
                                     (ignored)|String setConveyanceFlag()
                                     (ignored)|Long setItemkindNo()
                                     (ignored)|String setPolicyNo()
                                     (ignored)|String setPrecisionFlag()
                                     (ignored)|String setRemark()
                                     (ignored)|String setRiskCode()
Exception in thread "main" java.lang.NullPointerException
	at com.tuyang.beanutils.internal.javassist.impl.BeanCopier$$javassist0.copyBean(BeanCopier$$javassist0.java)
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:238)
	at cn.com.libertymutual.xuanbird.util.BeanUtilExt.copyBean(BeanUtilExt.java:116)
	at cn.com.libertymutual.xuanbird.prpall.nonmotor.service.impl.EndorseGenerateServiceImpl.main(EndorseGenerateServiceImpl.java:230)

**Comment by zhangdongkun** [comment]
----测试代码如下    

public static void main(String[] args) {
        AdjustDto adjustDto = new AdjustDto();
        adjustDto.setFlag(null);
        adjustDto.setSerialNo(null);
        PrpCadjustEntity prpCadjustEntity = new PrpCadjustEntity();
       System.out.println(BeanUtilExt.copyBean(adjustDto, prpCadjustEntity,AdjustEntityOpt.class));
    }

**Comment by yangtu222** [comment]
这个问题出在：
Long getSerialNo() |  long setSerialNo()
从Long对象到long数据类型。由于拷贝源的对象为空，无法映射到拷贝对象的数值类型，由于空对象，无法知晓缺省值，因此直接报错。
如果是Long对象到Long对象，那么是没问题的，或者是long数值到Long对象，也不会出现此问题。这个是程序员对于映射的设计问题，不是库的问题。
