### ISSUE TITLE
相同的的类名copy时报NullPointerException

### ISSUE THREAD

**Issue by zhangdongkun** [yangtu222/BeanUtils#34]
你好，
 出现一个影响比较大的一个问题，希望帮忙解决，谢谢！
1.第一种情况 : 
如下的例子，两个相同的类名在不同的包下，开发时没有问题，上线则报空指针（可以确定target 和source 都不为null，用了lombok 插件），线上环境是 spring boot  + docker
        cn.com.**.health.dto.sdbao.request.policyfree.OrderInfo policyFree_orderInfo = policyFreeRequestBody.getOrderInfo();
        UserInfo policyFree_applyUser = policyFreeRequestBody.getApplyUser();
        List<InsuredUserInfo> policyFree_insuredUsers = policyFreeRequestBody.getInsuredUsers();
        OrderInfo proposalOrder_orderInfo = BeanUtilExt.copyBean(policyFree_orderInfo, OrderInfo.class);

2.第二种情况
 不同的模块下（module）相同的包路径，不同的类 开发时没有问题，上线则报空指针。

------------附错误日志
java.lang.NullPointerException at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:238) at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:199) at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:135) at

**Comment by yangtu222** [comment]
不同的包下，相同的class名称？建议将class做import使用，或者写全class的package再试下。再就是看下是否是不同的模块的classpath不一致，找不到对应的class。

**Comment by zhangdongkun** [comment]
1.可以确定不是classpath的原因，因为copy的方法，换成 spring 的 BeanUtils.copyProperties
 org.springframework.beans.BeanUtils.copyProperties(proposalOrder_insuredUser, policyFree_insuredUser);
就正常了。
2.也不是相同类名的原因 ，不同的类名也会报错（在不同的模块）
        List<TbSdbaoBlackEntity> blackEntitiesTest = BeanCopyUtils.copyList(blackRequestDtos, TbSdbaoBlackEntity.class);
也会报错。
3.所有问题的共性都是本地开发没有问题，打包升级到线上就开始 NullPointerException

**Comment by yangtu222** [comment]
对于空指针的异常，从代码来看，似乎是无法创建TbSdbaoBlackEntity的实例造成。你尝试使用如下的使用方式看下：
TbSdbaoBlackEntity entity = new TbSdbaoBlackEntity();
entity = BeanCopyUtils.copyBean( source, entity); //传实例，而不是传class

如果上述还有问题，请检查下你的生产环境是否禁止使用javassist。如果是的话，那么可以使用：
BeanCopyConfig.instance().setBeanCopyFactory(ReflactBeanCopyFactory.class);
替换为通过遍历的方式完成此功能。

**Comment by zhangdongkun** [comment]
1.经过测试 BeanCopyUtils.copyBean 传实例也会空指针 ，所以基本确定是 javassist 无法生效的引起的。
    static  {
        BeanCopyConfig.instance().setBeanCopyFactory(ReflactBeanCopyFactory.class);
    }
改为反射后果然正常了。
问题虽然解决了但是还是有点疑问，a)是什么原因导致 javassist  禁用呢？可以在哪里设置吗？
