### ISSUE TITLE
不支持 return this 的 setter 方法，导致 setter 进去为 null

### ISSUE THREAD

**Issue by zengyufei** [yangtu222/BeanUtils#5]
class fromBean {
    private int id;
    private String name;

    // setter getter
}

@BeanCopySource(source = fromBean.class)
class toBean {
    private int id;
    private String name;

    /** 此处失效，凡是这种都失效  */
    public toBean setName(String name) {
        this.name = name;
        return this;
    }
   
}

**Comment by yangtu222** [comment]
hi，setter/getter为标准的java bean属性操作方式，不支持自定义方式。如果想自定义setter方式，可以fork代码，自己做下修改。
