### ISSUE TITLE
@BeanCopySource 不支持多次注解

### ISSUE THREAD

**Issue by zengyufei** [yangtu222/BeanUtils#6]
有些对象的值来自多个对象 mapper，需要注解多个 @BeanCopySource ，指定不同的 source

**Comment by yangtu222** [comment]
为了解决这个问题，可以使用Option Class的方式使用BeanCopySource，具体可参考readme。

**Comment by a-nuo** [comment]
目前存在一个问题，如果我第一个source A类中设置某个字段为@CopyCollection,第二个sourceB类中不存在该字段，则报错
Exception in thread "main" com.tuyang.beanutils.exception.BeanCopyException: BeanCopy: sourceB has no property 字段名 defined.!
	at com.tuyang.beanutils.internal.cache.BeanCopyCache.buildBeanCopyPropertyItem(BeanCopyCache.java:762)
	at com.tuyang.beanutils.internal.cache.BeanCopyCache.getBeanCopy(BeanCopyCache.java:117)
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:237)
	at TestBeanCopy.main(TestBeanCopy.java:56)

通过代码看，是由于com.tuyang.beanutils.internal.utils.PropertyUtils#getClassField在optionClass中如果不存在该字段，则在targetClass中查找，这个逻辑是否可以修改一下，以optionClass为准，做如下修改

`public static Field getClassField(Class<?> targetClass, Class<?> optionClass, String propertyName) {

        Field propertyField = null;

        if( optionClass != null ) {
            try {
                propertyField = optionClass.getDeclaredField(propertyName);
            } catch (NoSuchFieldException | SecurityException e) {
            }
           //修改默认逻辑，如果optionClass存在且没有propertyName字段，则不再在targetClass中查找
          return propertyField;
        }
        if( propertyField == null ) {

            Class<?> tryClass = targetClass;
            while( tryClass != null ) {
                try {
                    propertyField = tryClass.getDeclaredField(propertyName);
                    return propertyField;
                } catch (NoSuchFieldException | SecurityException e) {
                    tryClass = tryClass.getSuperclass();
                }
            }
        }
        return propertyField;
    }
`

**Comment by yangtu222** [comment]
能否将你的几个class简要列出来？否则不清楚具体问题处在什么位置。比如SourceA，SourceB都怎么定义，注解怎么写。

**Comment by a-nuo** [comment]
已经对SourceB中不存在的@CopyCollection字段做ignored=true处理；

**Comment by a-nuo** [comment]
````java
/// SourceA:
Class A{
  String date;
 String type;
List<Object> infoList;
}

// SourceB:
public class B {
    private String name;
    private String id;
}

// OptionB：
@BeanCopySource(source= B.class)
public class BOption{
    private String name;
    private String id;
    //需要忽略才会不报错
    @CopyCollection(targetClass= Object.class,ignored = true)
    private List<Object> infoList;//明细
}

//TargetClass
@BeanCopySource(source= A.class)
Classs C {
}
```

**掉用方式**
```java
A a = new A();
B b = new B(）；
C c = BeanCopyUtils.copyBean(a, C.class);
c= BeanCopyUtils.copyBean(b,c,BOption.class);
```

**除了需要设置ignored = true，是否有可以改进不报错的方式？**

**Comment by yangtu222** [comment]
其实报错的初衷是为了配置正确和逻辑正确。只有正确解决了报错，才能明确拷贝是否是想要的。这样就避免了一些查不出来的bug。
对于BeanCopyUtils.copyBean(b,c,BOption.class); 是想把b 的内容拷贝到c，而b中没有infoList，因此需要加入ignore=true. 另外一种写法为：@CopyProperty(ignored = true)，不必写成CopyCollection。

**Comment by a-nuo** [comment]
好的。
现在推荐项目组都用这个，速度杠杠的！👍
