### ISSUE TITLE
@CopyProperty 需要多次注解，而且需要判断 source 来自的 class 来进行选择性 setter

### ISSUE THREAD

**Issue by zengyufei** [yangtu222/BeanUtils#7]
有这样的需求,融合两个类 A 和 B 到一个类 C.

-------------------------------------------------------------------------------------------
@BeanCopySource(source = P.class)
@BeanCopySource(source = A.class)
@BeanCopySource(source = B.class)
class C {
    @CopyProperty(property = "id")
    @CopyProperty(property = "id", class=A.class)
    int aId;
    @CopyProperty(property = "id")
    @CopyProperty(property = "id", class=B.class)
    int bId;
}
-------------------------------------------------------------------------------------------

首先 @CopyProperty 是可以多次注解

如果 copyBean 只是是来自 A.class 则，只有 aId 有值。
如果 copyBean 只是是来自 B.class 则，只有 bId 有值。

如果 copyBean 只是是来自 H.class 则，只有 aId, bId 都有值。

**Comment by yangtu222** [comment]
多个source的注解混用会导致理解混乱，因此设计是采取单一原则。如果想自己支持的话，可以fork代码自己做修改。

**Comment by yangtu222** [comment]
如果target中存在CopyCollection注解的话，说明此属性需要拷贝，并按照集合的方式来拷贝。如果Option Class中没有定义，会找source中对应的字段说明；如果source中没有，那么可以在option class中写入此属性，然后标记igonre即可。不能因为option class中没有标记，就认为是ignore的，注解需要显示写出来。
