### ISSUE TITLE
BeanCopySource多个来源

### ISSUE THREAD

**Issue by melodicdeath** [yangtu222/BeanUtils#9]
@BeanCopySource(source={source1.class,sourc2.class})
public class clazz{
    @CopyProperty(property={"source1.field1","source2.field2"})
    private String field;
}

如果能支持这种是不是会更好？个人意见哈，肯定实现起来比较麻烦。

**Comment by yangtu222** [comment]
同 #7 一样，不支持注解多值情况，是为了防止在一个上面定义多值后理解混乱的情况。

**Comment by melodicdeath** [comment]
需要你这组件的项目可能一般是那种需要整合的项目或者有历史遗留问题的项目，不用常规的思维来设计可能会更好。到时候我有时间fork一份改一下试试。

**Comment by yangtu222** [comment]
如果是这样，可以采用定义不同的OptionClass的方式区别不同的拷贝对象和过程。应该可满足你的需求。
